'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var FETCH = exports.FETCH = 'SHENGNIAN/API/FETCH';
var FETCH_SUCCESS = exports.FETCH_SUCCESS = 'SHENGNIAN/API/FETCH_SUCCESS';
var FETCH_ERROR = exports.FETCH_ERROR = 'SHENGNIAN/API/FETCH_ERROR';
var FETCH_ONE = exports.FETCH_ONE = 'SHENGNIAN/API/FETCH_ONE';
var FETCH_ONE_SUCCESS = exports.FETCH_ONE_SUCCESS = 'SHENGNIAN/API/FETCH_ONE_SUCCESS';
var FETCH_ONE_ERROR = exports.FETCH_ONE_ERROR = 'SHENGNIAN/API/FETCH_ONE_ERROR';
var CREATE = exports.CREATE = 'SHENGNIAN/API/CREATE';
var CREATE_SUCCESS = exports.CREATE_SUCCESS = 'SHENGNIAN/API/CREATE_SUCCESS';
var CREATE_ERROR = exports.CREATE_ERROR = 'SHENGNIAN/API/CREATE_ERROR';
var UPDATE = exports.UPDATE = 'SHENGNIAN/API/UPDATE';
var UPDATE_SUCCESS = exports.UPDATE_SUCCESS = 'SHENGNIAN/API/UPDATE_SUCCESS';
var UPDATE_ERROR = exports.UPDATE_ERROR = 'SHENGNIAN/API/UPDATE_ERROR';
var DELETE = exports.DELETE = 'SHENGNIAN/API/DELETE';
var DELETE_SUCCESS = exports.DELETE_SUCCESS = 'SHENGNIAN/API/DELETE_SUCCESS';
var DELETE_ERROR = exports.DELETE_ERROR = 'SHENGNIAN/API/DELETE_ERROR';
var DELETE_BUCKET = exports.DELETE_BUCKET = 'SHENGNIAN/API/DELETE_BUCKET';
var DELETE_BUCKET_SUCCESS = exports.DELETE_BUCKET_SUCCESS = 'SHENGNIAN/API/DELETE_BUCKET_SUCCESS';
var DELETE_BUCKET_ERROR = exports.DELETE_BUCKET_ERROR = 'SHENGNIAN/API/DELETE_BUCKET_ERROR';
var CLEAR_ACTION_STATUS = exports.CLEAR_ACTION_STATUS = 'SHENGNIAN/API/CLEAR_ACTION_STATUS';
var API_CALL = exports.API_CALL = 'SHENGNIAN/API/API_CALL';
var GARBAGE_COLLECT = exports.GARBAGE_COLLECT = 'SHENGNIAN/API/GARBAGE_COLLECT';
var CLEAR_MODEL_DATA = exports.CLEAR_MODEL_DATA = 'SHENGNIAN/API/CLEAR_MODEL_DATA';